---
- name: Install apache
  hosts: all
  become: true
  tasks:

    - name: Install Apache
      apt:
        pkg:
          - apache2
        state: present

    - name: Copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /var/www/httpd.conf
        - src: httpd-vhosts.conf
          dest: /var/www/httpd-vhosts.conf

    - name: Ensure apache is started
      service:
        name: apache2
        state: started
        enabled: yes